# Generated by Django 5.2 on 2025-06-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameusers',
            managers=[
            ],
        ),
    ]
