# Generated by Django 3.2.5 on 2021-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_word', models.CharField(max_length=20, null=True)),
                ('alwd_incorrect_guess', models.PositiveIntegerField(default=0, null=True)),
                ('incorrect_guess_made', models.PositiveIntegerField(default=0, null=True)),
                ('incorrect_guess_remn', models.PositiveIntegerField(default=0, null=True)),
                ('game_status', models.CharField(choices=[('InProgress', 'InProgress'), ('Lost', 'Lost'), ('Won', 'Won')], default='InProgress', max_length=30)),
                ('cur_state_word', models.CharField(max_length=30)),
                ('guess_letter', models.CharField(max_length=5, null=True)),
                ('guess', models.CharField(choices=[('Correct', 'Correct'), ('Incorrect', 'Incorrect')], default=' ', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
