# Generated by Django 5.2 on 2025-06-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_word', models.CharField(max_length=20, null=True)),
                ('alwd_incorrect_guess', models.PositiveIntegerField(default=0, null=True)),
                ('incorrect_guess_made', models.PositiveIntegerField(default=0, null=True)),
                ('incorrect_guess_remn', models.PositiveIntegerField(default=0, null=True)),
                ('game_status', models.CharField(choices=[('InProgress', 'InProgress'), ('Lost', 'Lost'), ('Won', 'Won')], default='InProgress', max_length=30)),
                ('cur_state_word', models.CharField(max_length=30)),
                ('guess_letter', models.CharField(max_length=5, null=True)),
                ('guess', models.CharField(choices=[('Correct', 'Correct'), ('Incorrect', 'Incorrect')], default=' ', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_game_over', models.BooleanField(default=False)),
                ('gameuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
