import shortuuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.manager import GameUserManager

# Create your models here.
class GameUsers(AbstractUser):
    '''
    Creates a game user with short uuid as the public id,
    but it will create a ID as a autogenerated primary key
    In Django, unique=True automatically adds db_index=True
    In this model, email is used to login instead of username.
    '''

    public_id = models.CharField(default=shortuuid.uuid, max_length=22,
                                 unique=True, editable=False, null=True)
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = GameUserManager()
